// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AltaCal
{
    [Table("Arrangementer")]
    public partial class Arrangementer
    {
        [Key]
        [Column("ArrID")]
        public int ArrId { get; set; }
        [StringLength(255)]

        public string ArrNavn { get; set; }
        [StringLength(100)]

        public string Sted { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dato { get; set; }

        [StringLength(5)]
        public string Klokken { get; set; }


        [Column(TypeName = "date")]
        public DateTime? DatoSlutt { get; set; }

        [NotMapped]
        public string DatoSluttText => DatoSlutt?.ToShortDateString() + " " + Klokken;

        [StringLength(5)]
        public string KlokkenSlutt { get; set; }

        #region Handle dates and times

        /* Start */

        [NotMapped]
        public TimeSpan? KlokkenTime => !string.IsNullOrEmpty(Klokken) ? TimeSpan.Parse(Klokken) : (TimeSpan?)null;

        [NotMapped]
        public DateTime? DatoFull => Dato?.Date.Add(KlokkenTime.GetValueOrDefault());

        [NotMapped]
        public string DatoFullText => DatoFull?.ToShortDateString() + " " + DatoFull?.ToShortTimeString();
        
        /* Slutt */

        [NotMapped]
        public TimeSpan? KlokkenSluttTime => !string.IsNullOrEmpty(KlokkenSlutt) ? TimeSpan.Parse(KlokkenSlutt) : (TimeSpan?)null;

        [NotMapped]
        public DateTime? DatoSluttFull => DatoSlutt.GetValueOrDefault(Dato.GetValueOrDefault()).Date.Add(KlokkenSluttTime.GetValueOrDefault());

        [NotMapped]
        public string DatoSluttFullText => DatoSluttFull?.ToShortDateString() + " " + DatoSluttFull?.ToShortTimeString();

        #endregion
        //public float? Varighet { get; set; }

        //public bool Seilas { get; set; }
        //public bool Selskap { get; set; }
        //public bool OpenShip { get; set; }
        //public bool Dugnad { get; set; }
        //public bool? Deltagelse { get; set; }
        //public float? Kontingent { get; set; }
        //public short? Kostdag { get; set; }
        //public bool Overnatt { get; set; }
        //public bool Parkering { get; set; }
        //public bool SeskontAvheng { get; set; }
        //[Column("TurReturID")]
        //public int? TurReturId { get; set; }
        //public float? VaktlengdeSeilas { get; set; }
        //public float? VaktlengdeLand { get; set; }
        //public string InvitererSign { get; set; }
        //public string DeltagKvitt { get; set; }
        //public string AvmeldKvitt { get; set; }
        //public string ReiseInfo { get; set; }
        //public string ParkeringInfo { get; set; }
        //[Column("PSInfo")]
        //public string Psinfo { get; set; }
        //public string MerknadRulle { get; set; }
        //public string MerknadVaktlisteSeil { get; set; }
        //public bool Avlyst { get; set; }
        //public bool Sikkerhetskurs { get; set; }
        //public bool VentelisteArr { get; set; }
        //[Column("SesID")]
        //public int? SesId { get; set; }
        //public float? Gangetid { get; set; }
        //public float? Distanse { get; set; }
        //[Required]
        //[Column("SSMA_TimeStamp")]
        //public byte[] SsmaTimeStamp { get; set; }
    }
}