'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Arbeidsliste
        Public Property ID As Integer
        Public Property JobbID As Nullable(Of Integer)
        Public Property ArbID As Integer
    
        Public Overridable Property Jobb As Jobb
    
    End Class

End Namespace
