'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Brannapp
        Public Property ID As Integer
        Public Property TypeApparat As String
        Public Property Size As String
        Public Property Skiftet As String
        Public Property SlukkType As String
        Public Property FullVekt As String
        Public Property CO2VektDriv As String
        Public Property Plassering As String
        Public Property SvcDato As Nullable(Of Date)
        Public Property Intervall As Nullable(Of Date)
        Public Property Signatur As String
    
    End Class

End Namespace
