'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class DistanseTid
        Public Property SerID As Integer
        Public Property Seilas As String
        Public Property Dato As Nullable(Of Date)
        Public Property Merknad As String
        Public Property SeiltDistanse As Nullable(Of Single)
        Public Property TotalDistanse As Nullable(Of Single)
        Public Property SeiltTid As Nullable(Of Single)
        Public Property TotalTid As Nullable(Of Single)
        Public Property SSMA_TimeStamp As Byte()
    
    End Class

End Namespace
