'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Dokumenter
        Public Property DokID As Integer
        Public Property DokFork As String
        Public Property DokTittel As String
        Public Property Utgiver As String
        Public Property Utgitt As String
        Public Property Media As String
        Public Property Tegning As Nullable(Of Boolean)
        Public Property PlassID As Nullable(Of Integer)
        Public Property DokFil As String
        Public Property Antall As Nullable(Of Integer)
        Public Property HylleSkap As String
        Public Property Merknad As String
        Public Property DetaljID As Nullable(Of Integer)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property JobbDoks As ICollection(Of JobbDok) = New HashSet(Of JobbDok)
        Public Overridable Property UtstyrDoks As ICollection(Of UtstyrDok) = New HashSet(Of UtstyrDok)
    
    End Class

End Namespace
