'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class JobbDato
        Public Property SerID As Integer
        Public Property JobbID As Integer
        Public Property StartetDato As Nullable(Of Date)
        Public Property CompletedDato As Nullable(Of Date)
        Public Property NesteDato As Nullable(Of Date)
        Public Property NesteGange As Nullable(Of Integer)
        Public Property KontrollOK As Nullable(Of Boolean)
        Public Property Measurement As String
        Public Property KontrollResultat As String
        Public Property KontrollSign As String
        Public Property ArbeidBeskrivelse As String
        Public Property ArbeidSign As String
        Public Property ArbeidOK As Nullable(Of Boolean)
        Public Property Bilder As String
        Public Property Rapporter As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Jobb As Jobb
    
    End Class

End Namespace
