'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class JobbDok
        Public Property SerID As Integer
        Public Property JobbID As Nullable(Of Integer)
        Public Property DokID As Nullable(Of Integer)
        Public Property DokRef As String
        Public Property DokImg As String
    
        Public Overridable Property Dokumenter As Dokumenter
        Public Overridable Property Jobb As Jobb
    
    End Class

End Namespace
