'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class JobbNorm
        Public Property SerID As Integer
        Public Property JobbID As Nullable(Of Integer)
        Public Property NormID As Nullable(Of Integer)
    
        Public Overridable Property Jobb As Jobb
        Public Overridable Property JobbNorm1 As JobbNorm
        Public Overridable Property JobbNorm2 As JobbNorm
        Public Overridable Property Norm As Norm
    
    End Class

End Namespace
