'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Jobb
        Public Property JobbID As Integer
        Public Property StrID As Nullable(Of Integer)
        Public Property UtstyrID As Nullable(Of Integer)
        Public Property DetaljID As Nullable(Of Integer)
        Public Property PriID As Nullable(Of Integer)
        Public Property JobbKode As String
        Public Property JobbNavn As String
        Public Property JobbBeskrivelse As String
        Public Property Kontroll As Nullable(Of Boolean)
        Public Property Arbeid As Nullable(Of Boolean)
        Public Property IntTID As Nullable(Of Integer)
        Public Property IntervallDag As Nullable(Of Integer)
        Public Property IntervallUke As Nullable(Of Integer)
        Public Property IntervallMnd As Nullable(Of Single)
        Public Property IntervallYear As Nullable(Of Integer)
        Public Property Frist As Nullable(Of Date)
        Public Property Startet As Nullable(Of Boolean)
        Public Property Completed As Nullable(Of Boolean)
        Public Property IntervallGange As Nullable(Of Integer)
        Public Property CompletedGange As Nullable(Of Integer)
        Public Property NesteGange As Nullable(Of Integer)
        Public Property Dokking As Nullable(Of Boolean)
        Public Property Underveis As Nullable(Of Boolean)
        Public Property UnderLand As Nullable(Of Boolean)
        Public Property Dugnad As Nullable(Of Boolean)
        Public Property SendtAnsv As Nullable(Of Date)
        Public Property KvalSikr As String
        Public Property AnsvPerson As String
        Public Property StillingID As Nullable(Of Integer)
        Public Property Kriterier As String
        Public Property Skjema As String
        Public Property Merknad As String
        Public Property Flag As Nullable(Of Boolean)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Arbeidslistes As ICollection(Of Arbeidsliste) = New HashSet(Of Arbeidsliste)
        Public Overridable Property Struktur As Struktur
        Public Overridable Property Utstyr As Utstyr
        Public Overridable Property XIntervall As XIntervall
        Public Overridable Property XPrioritet As XPrioritet
        Public Overridable Property XStilling As XStilling
        Public Overridable Property JobbDatoes As ICollection(Of JobbDato) = New HashSet(Of JobbDato)
        Public Overridable Property JobbDoks As ICollection(Of JobbDok) = New HashSet(Of JobbDok)
        Public Overridable Property JobbNorms As ICollection(Of JobbNorm) = New HashSet(Of JobbNorm)
    
    End Class

End Namespace
