'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Kontakter
        Public Property ID As Integer
        Public Property Firma As String
        Public Property Navn As String
        Public Property Adr As String
        Public Property Poststed As String
        Public Property Land As String
        Public Property Telf As String
        Public Property Epost As String
        Public Property Kontakttype As String
        Public Property SSMA_TimeStamp As Byte()
    
    End Class

End Namespace
