'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Livvester
        Public Property ID As Integer
        Public Property TypeVest As String
        Public Property Plassering As String
        Public Property FastLivAntall As Nullable(Of Integer)
        Public Property StatusLivAntall As Nullable(Of Integer)
        Public Property FastAnnetAntall As Nullable(Of Integer)
        Public Property StatusAnnetAntall As Nullable(Of Integer)
        Public Property DatoTeltSist As Nullable(Of Date)
        Public Property Signatur As String
        Public Property Merknad As String
    
    End Class

End Namespace
