'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class MiddelKorr
        Public Property MiddelKorrID As Integer
        Public Property MiddelID As Nullable(Of Integer)
        Public Property AntKorrig As Nullable(Of Single)
        Public Property AntInn As Nullable(Of Single)
        Public Property AntTelt As Nullable(Of Single)
        Public Property AntStatusStart As Nullable(Of Single)
        Public Property Bruker As String
        Public Property Merknader As String
        Public Property KorrDato As Nullable(Of Date)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Middel As Middel
    
    End Class

End Namespace
