'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class MiddelDetalj
        Public Property MidDetID As Integer
        Public Property MiddelID As Nullable(Of Integer)
        Public Property PlassID As Nullable(Of Integer)
        Public Property Beholdning As Nullable(Of Single)
        Public Property AntKorrig As Nullable(Of Single)
        Public Property AntInn As Nullable(Of Single)
        Public Property AntTelt As Nullable(Of Single)
        Public Property Merknader As String
    
        Public Overridable Property Middel As Middel
        Public Overridable Property XPlassering As XPlassering
    
    End Class

End Namespace
