'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Middel
        Public Property MiddelID As Integer
        Public Property MiddelNavn As String
        Public Property MiddelTypeID As Integer
        Public Property EnhetVolum As String
        Public Property Emballasje As String
        Public Property PrisInn As Nullable(Of Single)
        Public Property StatusBeholdning As Nullable(Of Single)
        Public Property StatusDato As Nullable(Of Date)
        Public Property Merknader As String
        Public Property AntMin As Nullable(Of Single)
        Public Property Fabrikat As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property MiddelType As MiddelType
        Public Overridable Property MiddelDetaljs As ICollection(Of MiddelDetalj) = New HashSet(Of MiddelDetalj)
        Public Overridable Property MiddelKorrs As ICollection(Of MiddelKorr) = New HashSet(Of MiddelKorr)
    
    End Class

End Namespace
