'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class MiddelType
        Public Property MiddelTypeID As Integer
        Public Property MiddelType1 As String
        Public Property MiddelBeskrivelse As String
    
        Public Overridable Property Middels As ICollection(Of Middel) = New HashSet(Of Middel)
    
    End Class

End Namespace
