'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Norm
        Public Property NormID As Integer
        Public Property Gjelder As String
        Public Property Beskrivelse As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property JobbNorms As ICollection(Of JobbNorm) = New HashSet(Of JobbNorm)
    
    End Class

End Namespace
