'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace PMSDataAccess

    Partial Public Class PMSConnection
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=PMSConnection")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Arbeidsdatoers() As DbSet(Of Arbeidsdatoer)
        Public Overridable Property Arbeidslistes() As DbSet(Of Arbeidsliste)
        Public Overridable Property Brannapps() As DbSet(Of Brannapp)
        Public Overridable Property DistanseTids() As DbSet(Of DistanseTid)
        Public Overridable Property Dokumenters() As DbSet(Of Dokumenter)
        Public Overridable Property Jobbs() As DbSet(Of Jobb)
        Public Overridable Property JobbDatoes() As DbSet(Of JobbDato)
        Public Overridable Property JobbDoks() As DbSet(Of JobbDok)
        Public Overridable Property JobbNorms() As DbSet(Of JobbNorm)
        Public Overridable Property Kontakters() As DbSet(Of Kontakter)
        Public Overridable Property Livvesters() As DbSet(Of Livvester)
        Public Overridable Property Middels() As DbSet(Of Middel)
        Public Overridable Property MiddelDetaljs() As DbSet(Of MiddelDetalj)
        Public Overridable Property MiddelKorrs() As DbSet(Of MiddelKorr)
        Public Overridable Property MiddelTypes() As DbSet(Of MiddelType)
        Public Overridable Property Norms() As DbSet(Of Norm)
        Public Overridable Property Reservedels() As DbSet(Of Reservedel)
        Public Overridable Property ReservedelPlasses() As DbSet(Of ReservedelPlass)
        Public Overridable Property Sertifikats() As DbSet(Of Sertifikat)
        Public Overridable Property Sjekklistes() As DbSet(Of Sjekkliste)
        Public Overridable Property SjekkPunkts() As DbSet(Of SjekkPunkt)
        Public Overridable Property Strukturs() As DbSet(Of Struktur)
        Public Overridable Property Utstyrs() As DbSet(Of Utstyr)
        Public Overridable Property UtstyrDoks() As DbSet(Of UtstyrDok)
        Public Overridable Property UtstyrGangetids() As DbSet(Of UtstyrGangetid)
        Public Overridable Property UtstyrPlasserings() As DbSet(Of UtstyrPlassering)
        Public Overridable Property UtstyrReserves() As DbSet(Of UtstyrReserve)
        Public Overridable Property XDetaljs() As DbSet(Of XDetalj)
        Public Overridable Property XEnhets() As DbSet(Of XEnhet)
        Public Overridable Property XIntervalls() As DbSet(Of XIntervall)
        Public Overridable Property XParameters() As DbSet(Of XParameter)
        Public Overridable Property XPersons() As DbSet(Of XPerson)
        Public Overridable Property XPlasserings() As DbSet(Of XPlassering)
        Public Overridable Property XPrioritets() As DbSet(Of XPrioritet)
        Public Overridable Property XStillings() As DbSet(Of XStilling)
        Public Overridable Property vwStrukturTres() As DbSet(Of vwStrukturTre)
    
    End Class

End Namespace
