'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Reservedel
        Public Property DelID As Integer
        Public Property DelNavn As String
        Public Property Fabrikat As String
        Public Property DelNummer As String
        Public Property NATOnr As String
        Public Property Spesifikasjon As String
        Public Property EnhetVolum As Nullable(Of Single)
        Public Property Emballasje As String
        Public Property EmbMerking As String
        Public Property PrisInn As Nullable(Of Single)
        Public Property StatusDato As Nullable(Of Date)
        Public Property StatusBeholdning As Nullable(Of Integer)
        Public Property AntMin As Nullable(Of Integer)
        Public Property Merknad As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property ReservedelPlasses As ICollection(Of ReservedelPlass) = New HashSet(Of ReservedelPlass)
        Public Overridable Property UtstyrReserves As ICollection(Of UtstyrReserve) = New HashSet(Of UtstyrReserve)
    
    End Class

End Namespace
