'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class ReservedelPlass
        Public Property DelPlassID As Integer
        Public Property DelID As Nullable(Of Integer)
        Public Property PlassID As Nullable(Of Integer)
        Public Property Beholdning As Nullable(Of Integer)
        Public Property AntKorrig As Nullable(Of Integer)
        Public Property AntInn As Nullable(Of Integer)
        Public Property AntTelt As Nullable(Of Integer)
        Public Property Merknader As String
    
        Public Overridable Property Reservedel As Reservedel
        Public Overridable Property XPlassering As XPlassering
    
    End Class

End Namespace
