'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Sertifikat
        Public Property SertID As Integer
        Public Property UtstyrID As Nullable(Of Integer)
        Public Property SertNavn As String
        Public Property SertNummer As String
        Public Property SertDato As Nullable(Of Date)
        Public Property SertUtsteder As String
        Public Property Intervall As Nullable(Of Integer)
        Public Property FornyDato As Nullable(Of Date)
        Public Property Gjelder As String
        Public Property Merknad As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Utstyr As Utstyr
    
    End Class

End Namespace
