'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class SjekkPunkt
        Public Property SjkDetID As Integer
        Public Property SjkID As Integer
        Public Property SjkSer As Short
        Public Property SjkSubTittel As String
        Public Property SjkInnhold As String
        Public Property SjkNB As String
    
    End Class

End Namespace
