'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Sjekkliste
        Public Property SjkID As Integer
        Public Property SjkTittel As String
        Public Property SjkBruk As String
        Public Property DetaljID As Nullable(Of Integer)
        Public Property StrID As Nullable(Of Integer)
        Public Property SjkBrukesNår As String
        Public Property SjkBrukesAv As String
    
        Public Overridable Property Struktur As Struktur
        Public Overridable Property XDetalj As XDetalj
    
    End Class

End Namespace
