'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Struktur
        Public Property StrID As Integer
        Public Property StrNr As String
        Public Property Trinn As Integer
        Public Property StrElement As String
        Public Property StrKomponenter As String
        Public Property ParentID As Nullable(Of Integer)
        Public Property AntUtstyr As Nullable(Of Integer)
        Public Property Merknad As String
        Public Property Benyttes As Nullable(Of Boolean)
        Public Property Lavest As Nullable(Of Boolean)
        Public Property DetaljID As Nullable(Of Integer)
        Public Property StrNrTidl As String
        Public Property StrSubNr As String
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Jobbs As ICollection(Of Jobb) = New HashSet(Of Jobb)
        Public Overridable Property Sjekklistes As ICollection(Of Sjekkliste) = New HashSet(Of Sjekkliste)
        Public Overridable Property XDetalj As XDetalj
        Public Overridable Property Utstyrs As ICollection(Of Utstyr) = New HashSet(Of Utstyr)
        Public Overridable Property UtstyrReserves As ICollection(Of UtstyrReserve) = New HashSet(Of UtstyrReserve)
    
    End Class

End Namespace
