'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class UtstyrReserve
        Public Property SerID As Integer
        Public Property UtstyrID As Nullable(Of Integer)
        Public Property DelID As Nullable(Of Integer)
        Public Property StrID As Nullable(Of Integer)
    
        Public Overridable Property Reservedel As Reservedel
        Public Overridable Property Struktur As Struktur
        Public Overridable Property Utstyr As Utstyr
    
    End Class

End Namespace
