'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class UtstyrGangetid
        Public Property UGID As Integer
        Public Property UtstyrID As Nullable(Of Integer)
        Public Property GangetidUke As Nullable(Of Integer)
        Public Property GangetidTotal As Nullable(Of Integer)
        Public Property Merknad As String
        Public Property LoggDato As Nullable(Of Date)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Utstyr As Utstyr
    
    End Class

End Namespace
