'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class UtstyrDok
        Public Property SerID As Integer
        Public Property UtstyrID As Nullable(Of Integer)
        Public Property DokID As Nullable(Of Integer)
    
        Public Overridable Property Dokumenter As Dokumenter
        Public Overridable Property Utstyr As Utstyr
    
    End Class

End Namespace
