'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class Utstyr
        Public Property UtstyrID As Integer
        Public Property Utstyr1 As String
        Public Property UtstyrNr As String
        Public Property Fabrikat As String
        Public Property Modell As String
        Public Property StrID As Nullable(Of Integer)
        Public Property Kapasitet As String
        Public Property Serienr As String
        Public Property NATOnr As String
        Public Property DetaljID As Nullable(Of Integer)
        Public Property KravSertifikat As Nullable(Of Boolean)
        Public Property Reserve As Nullable(Of Boolean)
        Public Property GangetidBasis As Nullable(Of Boolean)
        Public Property GangetidStatus As Nullable(Of Integer)
        Public Property ByggeYear As String
        Public Property AntJobber As Nullable(Of Integer)
        Public Property AntJobberUtf As Nullable(Of Integer)
        Public Property Merknad As String
        Public Property PlassID As Nullable(Of Integer)
        Public Property Antall As Nullable(Of Integer)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property Jobbs As ICollection(Of Jobb) = New HashSet(Of Jobb)
        Public Overridable Property Sertifikats As ICollection(Of Sertifikat) = New HashSet(Of Sertifikat)
        Public Overridable Property Struktur As Struktur
        Public Overridable Property XDetalj As XDetalj
        Public Overridable Property XPlassering As XPlassering
        Public Overridable Property UtstyrDoks As ICollection(Of UtstyrDok) = New HashSet(Of UtstyrDok)
        Public Overridable Property UtstyrGangetids As ICollection(Of UtstyrGangetid) = New HashSet(Of UtstyrGangetid)
        Public Overridable Property UtstyrPlasserings As ICollection(Of UtstyrPlassering) = New HashSet(Of UtstyrPlassering)
        Public Overridable Property UtstyrReserves As ICollection(Of UtstyrReserve) = New HashSet(Of UtstyrReserve)
    
    End Class

End Namespace
