'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class vwStrukturTre
        Public Property StrID As Integer
        Public Property StrNr As String
        Public Property StrElement As String
        Public Property ParentID As Nullable(Of Integer)
        Public Property Benyttes As Nullable(Of Boolean)
        Public Property StrNavn As String
    
    End Class

End Namespace
