'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class XDetalj
        Public Property DetaljID As Integer
        Public Property DetaljNavn As String
        Public Property StillingID As Nullable(Of Integer)
    
        Public Overridable Property Sjekklistes As ICollection(Of Sjekkliste) = New HashSet(Of Sjekkliste)
        Public Overridable Property Strukturs As ICollection(Of Struktur) = New HashSet(Of Struktur)
        Public Overridable Property Utstyrs As ICollection(Of Utstyr) = New HashSet(Of Utstyr)
        Public Overridable Property XStilling As XStilling
    
    End Class

End Namespace
