'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class XParameter
        Public Property StdID As Integer
        Public Property HovedBeholdning As String
        Public Property CCBeholdning As String
        Public Property HovedSertifikat As String
        Public Property CCSertifikat As String
        Public Property HovedProcure As String
        Public Property CCProcure As String
        Public Property HovedNav As String
        Public Property CCNav As String
        Public Property FilbaneLager As String
    
    End Class

End Namespace
