'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PMSDataAccess

    Partial Public Class XPlassering
        Public Property PlassID As Integer
        Public Property Plassering As String
        Public Property Reserve As Nullable(Of Boolean)
        Public Property Middel As Nullable(Of Boolean)
        Public Property Utstyr As Nullable(Of Boolean)
        Public Property Jobb As Nullable(Of Boolean)
        Public Property Dok As Nullable(Of Boolean)
        Public Property SSMA_TimeStamp As Byte()
    
        Public Overridable Property MiddelDetaljs As ICollection(Of MiddelDetalj) = New HashSet(Of MiddelDetalj)
        Public Overridable Property ReservedelPlasses As ICollection(Of ReservedelPlass) = New HashSet(Of ReservedelPlass)
        Public Overridable Property Utstyrs As ICollection(Of Utstyr) = New HashSet(Of Utstyr)
        Public Overridable Property UtstyrPlasserings As ICollection(Of UtstyrPlassering) = New HashSet(Of UtstyrPlassering)
    
    End Class

End Namespace
